### ISSUE TITLE
Funcionalidade do Projeto

### ISSUE THREAD

**Issue by renanzupa** [prodest/api-detran#23]
Pessoal, tudo bem ?

Este projeto é funcional apenas para um estado especifico ou é funcional para todo o território nacional ?

Posso utilizar a API para consultar Débitos e dados de veículos do estado de SP ?

Obrigado desde já.

**Comment by vizeke** [comment]
fala.. @renanzupa 

Essa API foi desenvolvida pelo Prodest no Espírito Santo, com o intuito inicial de fornecer informações para um aplicativo que estamos desenvolvendo o ES na Palma da Mão.

Cada Detran/Ciretran tem uma abrangência estadual ou distrital. No caso dessa API, nós temos integração apenas com sistema do DETRAN do estado do Espírito Santo. Assim, só é possível realizar consultas de carros ou CNHs do ES.

**Comment by xereda** [comment]
Olá,

Podem me dizer que há api pública aqui para o estado de Santa Catarina?

**Comment by alvarollmenezes** [comment]
Bom dia @xereda, 

Como somos do Governo do Estado do Espírito Santo, não temos essas informações sobre Santa Catarina.

O que posso te indicar é que entre em contato com o CIASC (http://www.ciasc.sc.gov.br) para obter mais informações, imagino que eles possam te orientar melhor.
